# permissions for end users to edit moons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moon-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - moons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - moons/status
  verbs:
  - get
