# permissions for end users to view moons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moon-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - moons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - moons/status
  verbs:
  - get
